import stdlib.Slice
import sympy.Basic


@[main]
private lemma main
-- given
  (n i : ℕ) :
-- imply
  Slice.Add_Mul_DivSub1Sign_2 n i = i := by
-- proof
  unfold Slice.Add_Mul_DivSub1Sign_2
  cases i <;> simp


/--
this might be automatically generated by input specification of the main lemma
-/
@[main]
private lemma one
-- given
  (n : ℕ) :
-- imply
  Slice.Add_Mul_DivSub1Sign_2 n 1 = 1 := by
-- proof
  apply main


@[main]
private lemma zero
-- given
  (n : ℕ) :
-- imply
  Slice.Add_Mul_DivSub1Sign_2 n 0 = 0 := by
-- proof
  apply main


-- created on 2025-05-06
-- updated on 2025-05-11
