import torch.Tensor.exp
import torch.Tensor.sin
import torch.Tensor.cos
import torch.Tensor.cot
import torch.Tensor.tan
import torch.Tensor.pow
import torch.Tensor.log
import torch.utils
import torch.Tensor
import torch.Tensor.shape
import torch.Tensor.sum
import torch.Tensor.mean
import torch.Tensor.bmm
import torch.Tensor.prod
import torch.Tensor.reshape
import torch.Tensor.unsqueeze
import torch.Tensor.repeat
import torch.Tensor.permute
import torch.Tensor.item
import torch.eye
import torch.Tensor.masked_fill
import torch.Tensor.tril
import torch.Tensor.triu
import torch.linalg
import torch.linalg.inv
import torch.linalg.det
import torch.nn.functional.softmax
import torch.nn.functional.sigmoid
import torch.nn.functional.relu
import torch.Tensor.select
import torch.hstack
import torch.Tensor.aminmax
import torch.Tensor.min
import torch.Tensor.max
import torch.Tensor.argmin
import torch.Tensor.argmax
import torch.Tensor.isclose
