
import Mathlib.RingTheory.TwoSidedIdeal.Basic
import Mathlib.RingTheory.TwoSidedIdeal.Operations
import Mathlib.RingTheory.TwoSidedIdeal.Lattice
import Mathlib.RingTheory.TwoSidedIdeal.Kernel
import Mathlib.Order.Zorn
import Mathlib.Algebra.CharP.Defs
import Mathlib.Algebra.Field.Basic
import Mathlib.Algebra.Algebra.Subalgebra.Lattice
import Mathlib.Algebra.Algebra.ZMod
import Mathlib.LinearAlgebra.Span.Basic
import Mathlib.RingTheory.Finiteness.Basic
import Mathlib.RingTheory.Finiteness.Cardinality
import Mathlib.RingTheory.IntegralDomain
import Mathlib.RingTheory.LittleWedderburn
import Mathlib.Algebra.Polynomial.Roots
import Mathlib.Algebra.Polynomial.Splits
import Mathlib.Algebra.Polynomial.Eval.Defs
import Mathlib.Algebra.CharP.Lemmas
import Mathlib.Algebra.Module.LinearMap.End
import Mathlib.FieldTheory.Finite.Basic
import Mathlib.GroupTheory.OrderOfElement


namespace Int.Ring.JacobsonCommutativity

open scoped BigOperators

/-!
# Jacobson commutativity

If every `x : R` satisfies `x ^ n = x` for some `n > 1` (depending on `x`),
then `R` is commutative. The proof goes through noncommutative prime ideals:
a periodic ring is reduced, hence the prime radical is `0` (primes separating
points come from Zorn's lemma applied to ideals disjoint from the `m`-system
`{x ^ n}`), and a prime periodic ring is a domain, hence a division ring,
hence a field by Herstein's torsion theorem.

Primary source: N. Jacobson, “Structure Theory for Algebraic Algebras of Bounded Degree”,
Annals of Mathematics 46(4) (1945), 695–707, DOI 10.2307/1969205.
The periodic-division-ring step is Herstein's torsion theorem, proved here via the
Wamsley/Nagahara–Tominaga operator argument over the finite subfield generated by one
element (using `littleWedderburn`).
-/

variable {R : Type*} [Ring R]

/-- A two-sided ideal is prime if it is proper and `a * R * b ⊆ P` forces
`a ∈ P` or `b ∈ P`. This is the noncommutative notion; Mathlib's
`Ideal.IsPrime` is the (stronger) completely prime notion. -/
def IsPrimeIdeal (P : TwoSidedIdeal R) : Prop :=
  P ≠ ⊤ ∧ ∀ a b : R, (∀ r : R, a * r * b ∈ P) → a ∈ P ∨ b ∈ P

theorem IsPrimeIdeal.ne_top {P : TwoSidedIdeal R} (hP : IsPrimeIdeal P) :
    P ≠ ⊤ :=
  hP.1

theorem IsPrimeIdeal.mem_or_mem {P : TwoSidedIdeal R} (hP : IsPrimeIdeal P)
    {a b : R} (h : ∀ r : R, a * r * b ∈ P) : a ∈ P ∨ b ∈ P :=
  hP.2 a b h

/-- In a periodic ring, a power collapsing to zero forces the element to zero:
from `x ^ m = 0` and `x ^ n = x`, iterate to `x ^ (n ^ m) = x` and split the
exponent. In particular a periodic ring is reduced. -/
private lemma eq_zero_of_pow_eq_zero {x : R} {m : ℕ}
    (h : ∀ x : R, ∃ n : ℕ, 1 < n ∧ x ^ n = x)
    (hx : x ^ m = 0) : x = 0 := by
  obtain ⟨n, hn, hnx⟩ := h x
  have hpow : ∀ r : ℕ, x ^ (n ^ r) = x := by
    intro r
    induction r with
    | zero => rw [pow_zero, pow_one]
    | succ r ih =>
      rw [pow_succ, pow_mul, ih]
      exact hnx
  have hge : m ≤ n ^ m := by
    have h2 : 2 ^ m ≤ n ^ m := Nat.pow_le_pow_left hn m
    have hlt : m < 2 ^ m := Nat.lt_two_pow_self
    omega
  have hxN : x ^ (n ^ m) = x := hpow m
  obtain ⟨k, hk⟩ : ∃ k, n ^ m = m + k := ⟨n ^ m - m, by omega⟩
  rw [hk, pow_add, hx, zero_mul] at hxN
  exact hxN.symm

/-- An `m`-system: a nonempty set avoiding `0`, closed under joining pairs
through `R`. -/
def IsMSystem (M : Set R) : Prop :=
  M.Nonempty ∧ 0 ∉ M ∧ ∀ a b : R, a ∈ M → b ∈ M → ∃ r : R, a * r * b ∈ M

/-- Products across principal two-sided ideals over an `a * R * b` relation,
by double `span_induction` (the side conditions absorb into the `∀ r`). -/
private lemma span_mul_span_mem {P : TwoSidedIdeal R} {a b : R}
    (h : ∀ r : R, a * r * b ∈ P)
    {t₁ : R} (ht₁ : t₁ ∈ TwoSidedIdeal.span {a})
    {t₂ : R} (ht₂ : t₂ ∈ TwoSidedIdeal.span {b})
    (r : R) : t₁ * r * t₂ ∈ P := by
  revert r
  refine TwoSidedIdeal.span_induction
    (p := fun t₁ _ => ∀ r : R, t₁ * r * t₂ ∈ P) ?_ ?_ ?_ ?_ ?_ ?_ ht₁
  · intro z hz
    rw [Set.mem_singleton_iff.mp hz]
    refine TwoSidedIdeal.span_induction
      (p := fun t₂ _ => ∀ r : R, a * r * t₂ ∈ P) ?_ ?_ ?_ ?_ ?_ ?_ ht₂
    · intro w hw r
      rw [Set.mem_singleton_iff.mp hw]
      exact h r
    · intro r
      rw [mul_zero]
      exact zero_mem _
    · intro x y hx hy ihx ihy r
      have e : a * r * (x + y) = a * r * x + a * r * y := by rw [mul_add]
      rw [e]
      exact add_mem (ihx r) (ihy r)
    · intro x hx ihx r
      have e : a * r * (-x) = -(a * r * x) := by rw [mul_neg]
      rw [e]
      exact neg_mem (ihx r)
    · intro c x hx ihx r
      have e : a * r * (c * x) = a * (r * c) * x := by simp only [mul_assoc]
      rw [e]
      exact ihx (r * c)
    · intro c x hx ihx r
      have e : a * r * (x * c) = (a * r * x) * c := by simp only [mul_assoc]
      rw [e]
      exact TwoSidedIdeal.mul_mem_right _ _ _ (ihx r)
  · intro r
    rw [zero_mul, zero_mul]
    exact zero_mem _
  · intro x y hx hy ihx ihy r
    have e : (x + y) * r * t₂ = x * r * t₂ + y * r * t₂ := by
      rw [add_mul, add_mul]
    rw [e]
    exact add_mem (ihx r) (ihy r)
  · intro x hx ihx r
    have e : (-x) * r * t₂ = -(x * r * t₂) := by rw [neg_mul, neg_mul]
    rw [e]
    exact neg_mem (ihx r)
  · intro c x hx ihx r
    have e : (c * x) * r * t₂ = c * (x * r * t₂) := by simp only [mul_assoc]
    rw [e]
    exact TwoSidedIdeal.mul_mem_left _ _ _ (ihx r)
  · intro c x hx ihx r
    have e : (x * c) * r * t₂ = x * (c * r) * t₂ := by simp only [mul_assoc]
    rw [e]
    exact ihx (c * r)

/-- An ideal maximal among those disjoint from an `m`-system is prime. -/
private lemma isPrimeIdeal_of_maximal_disjoint {M : Set R} (hM : IsMSystem M)
    {P : TwoSidedIdeal R} (hPdis : Disjoint (P : Set R) M)
    (hmax : ∀ Q : TwoSidedIdeal R, P ≤ Q → Disjoint (Q : Set R) M → Q = P) :
    IsPrimeIdeal P := by
  obtain ⟨m₀, hm₀⟩ := hM.1
  have hPtop : P ≠ ⊤ := by
    intro hcon
    have hmem : m₀ ∈ P := hcon ▸ TwoSidedIdeal.mem_top R
    exact hPdis.notMem_of_mem_left (SetLike.mem_coe.mpr hmem) hm₀
  refine ⟨hPtop, fun a b hab => ?_⟩
  by_contra hcon
  rw [not_or] at hcon
  obtain ⟨ha, hb⟩ := hcon
  set A : TwoSidedIdeal R := P ⊔ TwoSidedIdeal.span {a} with hA
  have hpltA : P < A := by
    refine lt_of_le_of_ne le_sup_left ?_
    intro hcon2
    apply ha
    rw [hcon2]
    exact TwoSidedIdeal.mem_sup_right
      (SetLike.mem_coe.mp (TwoSidedIdeal.subset_span (Set.mem_singleton a)))
  have hAnondis : ¬ Disjoint (A : Set R) M := by
    intro hdis
    exact absurd (hmax A le_sup_left hdis) (ne_of_gt hpltA)
  obtain ⟨m₁, hm₁A, hm₁M⟩ := Set.not_disjoint_iff.mp hAnondis
  set B : TwoSidedIdeal R := P ⊔ TwoSidedIdeal.span {b} with hB
  have hpltB : P < B := by
    refine lt_of_le_of_ne le_sup_left ?_
    intro hcon2
    apply hb
    rw [hcon2]
    exact TwoSidedIdeal.mem_sup_right
      (SetLike.mem_coe.mp (TwoSidedIdeal.subset_span (Set.mem_singleton b)))
  have hBnondis : ¬ Disjoint (B : Set R) M := by
    intro hdis
    exact absurd (hmax B le_sup_left hdis) (ne_of_gt hpltB)
  obtain ⟨m₂, hm₂B, hm₂M⟩ := Set.not_disjoint_iff.mp hBnondis
  obtain ⟨r, hrM⟩ := hM.2.2 m₁ m₂ hm₁M hm₂M
  have hmem : m₁ * r * m₂ ∈ P := by
    obtain ⟨p₁, hp₁, t₁, ht₁, e₁⟩ := TwoSidedIdeal.mem_sup.mp hm₁A
    obtain ⟨p₂, hp₂, t₂, ht₂, e₂⟩ := TwoSidedIdeal.mem_sup.mp hm₂B
    have hexpand : m₁ * r * m₂
        = p₁ * r * p₂ + p₁ * r * t₂ + (t₁ * r * p₂ + t₁ * r * t₂) := by
      rw [← e₁, ← e₂, add_mul, add_mul, mul_add, mul_add]
    rw [hexpand]
    refine add_mem (add_mem ?_ ?_) (add_mem ?_ ?_)
    · exact TwoSidedIdeal.mul_mem_right _ _ _
        (TwoSidedIdeal.mul_mem_right _ _ _ hp₁)
    · exact TwoSidedIdeal.mul_mem_right _ _ _
        (TwoSidedIdeal.mul_mem_right _ _ _ hp₁)
    · exact TwoSidedIdeal.mul_mem_left _ _ _ hp₂
    · exact span_mul_span_mem hab ht₁ ht₂ r
  exact hPdis.notMem_of_mem_left (SetLike.mem_coe.mpr hmem) hrM

/-- The union of a nonempty chain of ideals, as a two-sided ideal. -/
private def chainUnion (c : Set (TwoSidedIdeal R)) (hc : IsChain (· ≤ ·) c)
    (hne : c.Nonempty) : TwoSidedIdeal R :=
  TwoSidedIdeal.mk' (⋃ J ∈ c, (J : Set R))
    (by
      obtain ⟨J₀, hJ₀⟩ := hne
      exact Set.mem_biUnion hJ₀ (zero_mem J₀))
    (by
      intro x y hx hy
      obtain ⟨J₁, hJ₁, hxJ₁⟩ := Set.mem_iUnion₂.mp hx
      obtain ⟨J₂, hJ₂, hyJ₂⟩ := Set.mem_iUnion₂.mp hy
      by_cases heq : J₁ = J₂
      · subst heq
        exact Set.mem_biUnion hJ₂ (add_mem hxJ₁ hyJ₂)
      · rcases hc hJ₁ hJ₂ heq with hle | hle
        · exact Set.mem_biUnion hJ₂ (add_mem (hle hxJ₁) hyJ₂)
        · exact Set.mem_biUnion hJ₁ (add_mem hxJ₁ (hle hyJ₂)))
    (by
      intro x hx
      obtain ⟨J, hJ, hxJ⟩ := Set.mem_iUnion₂.mp hx
      exact Set.mem_biUnion hJ (neg_mem hxJ))
    (by
      intro x y hy
      obtain ⟨J, hJ, hyJ⟩ := Set.mem_iUnion₂.mp hy
      exact Set.mem_biUnion hJ (TwoSidedIdeal.mul_mem_left _ _ _ hyJ))
    (by
      intro x y hx
      obtain ⟨J, hJ, hxJ⟩ := Set.mem_iUnion₂.mp hx
      exact Set.mem_biUnion hJ (TwoSidedIdeal.mul_mem_right _ _ _ hxJ))

private lemma chainUnion_mem (c : Set (TwoSidedIdeal R))
    (hc : IsChain (· ≤ ·) c) (hne : c.Nonempty) (x : R) :
    x ∈ chainUnion c hc hne ↔ x ∈ ⋃ J ∈ c, (J : Set R) :=
  TwoSidedIdeal.mem_mk' _ _ _ _ _ _ _

/-- Prime ideals separate points from `m`-systems: Zorn on ideals disjoint
from `M`, with chain unions as upper bounds. -/
private lemma exists_primeIdeal_disjoint {M : Set R} (hM : IsMSystem M)
    {I : TwoSidedIdeal R} (hIdis : Disjoint (I : Set R) M) :
    ∃ P : TwoSidedIdeal R,
      I ≤ P ∧ Disjoint (P : Set R) M ∧ IsPrimeIdeal P := by
  obtain ⟨P, hPmax⟩ := zorn_le₀
    {J : TwoSidedIdeal R | I ≤ J ∧ Disjoint (J : Set R) M}
    (fun c hcs hc => by
      by_cases hne : c.Nonempty
      · refine ⟨chainUnion c hc hne, ⟨?_, ?_⟩, fun J hJc => ?_⟩
        · obtain ⟨J₀, hJ₀⟩ := hne
          intro x hxI
          exact (chainUnion_mem _ _ _ _).mpr
            (Set.mem_biUnion hJ₀ ((hcs hJ₀).1 hxI))
        · intro x hxU hxM y hyx
          have hyU : y ∈ ⋃ J ∈ c, (J : Set R) :=
            (chainUnion_mem _ _ _ _).mp (SetLike.mem_coe.mp (hxU hyx))
          obtain ⟨J, hJc, hyJ⟩ := Set.mem_iUnion₂.mp hyU
          exact (hcs hJc).2.notMem_of_mem_left
            (SetLike.mem_coe.mpr hyJ) (hxM hyx)
        · intro x hxJ
          exact (chainUnion_mem _ _ _ _).mpr (Set.mem_biUnion hJc hxJ)
      · refine ⟨I, ⟨le_rfl, hIdis⟩, fun J hJc => ?_⟩
        exact absurd ⟨J, hJc⟩ hne)
  obtain ⟨hPI, hPdis⟩ := hPmax.prop
  refine ⟨P, hPI, hPdis, ?_⟩
  apply isPrimeIdeal_of_maximal_disjoint hM hPdis
  intro Q hPQ hQdis
  have hQs : Q ∈ {J : TwoSidedIdeal R | I ≤ J ∧ Disjoint (J : Set R) M} :=
    ⟨hPI.trans hPQ, hQdis⟩
  exact le_antisymm (hPmax.le_of_ge hQs hPQ) hPQ

/-- Powers of a nonzero periodic element form an `m`-system. -/
private lemma isMSystem_powers {a : R}
    (h : ∀ x : R, ∃ n : ℕ, 1 < n ∧ x ^ n = x) (ha : a ≠ 0) :
    IsMSystem {y : R | ∃ n : ℕ, 1 ≤ n ∧ y = a ^ n} := by
  refine ⟨⟨a, 1, le_rfl, (pow_one a).symm⟩, ?_, ?_⟩
  · intro hcon
    obtain ⟨n, hn, hmem⟩ := hcon
    exact ha (eq_zero_of_pow_eq_zero h hmem.symm)
  · intro x y hx hy
    obtain ⟨i, hi, rfl⟩ := hx
    obtain ⟨j, hj, rfl⟩ := hy
    refine ⟨1, i + j, by omega, ?_⟩
    rw [mul_one, pow_add]

/-- Every nonzero element of a periodic ring lies outside some prime ideal. -/
private lemma exists_primeIdeal_not_mem {a : R}
    (h : ∀ x : R, ∃ n : ℕ, 1 < n ∧ x ^ n = x) (ha : a ≠ 0) :
    ∃ P : TwoSidedIdeal R, IsPrimeIdeal P ∧ a ∉ P := by
  have hM : IsMSystem {y : R | ∃ n : ℕ, 1 ≤ n ∧ y = a ^ n} :=
    isMSystem_powers h ha
  obtain ⟨P, hIP, hPdis, hPprime⟩ :=
    exists_primeIdeal_disjoint hM (I := ⊥) (by
      intro x hxU hxM y hyx
      have hy0 : y = 0 :=
        (TwoSidedIdeal.mem_bot _).mp (SetLike.mem_coe.mp (hxU hyx))
      have hym : y ∈ {y : R | ∃ n : ℕ, 1 ≤ n ∧ y = a ^ n} := hxM hyx
      rw [hy0] at hym
      exact hM.2.1 hym)
  refine ⟨P, hPprime, fun hamem => ?_⟩
  exact hPdis.notMem_of_mem_left (SetLike.mem_coe.mpr hamem)
    ⟨1, le_rfl, (pow_one a).symm⟩

/-- A prime periodic ring is a domain: `xy = 0` forces `xRy = 0` via
nilpotent-squaring, so primeness kills a factor. -/
private lemma noZeroDivisors_of_prime_of_periodic {S : Type*} [Ring S]
    (hprime : IsPrimeIdeal (⊥ : TwoSidedIdeal S))
    (h : ∀ x : S, ∃ n : ℕ, 1 < n ∧ x ^ n = x) :
    NoZeroDivisors S := by
  refine ⟨?_⟩
  intro x y hxy
  have hyx : y * x = 0 := by
    have h1 : (y * x) ^ 2 = 0 := by
      have e : (y * x) ^ 2 = y * (x * y) * x := by
        simp only [pow_two, mul_assoc]
      rw [e, hxy, mul_zero, zero_mul]
    exact eq_zero_of_pow_eq_zero h h1
  have hall : ∀ r : S, x * r * y = 0 := by
    intro r
    have h1 : (x * r * y) ^ 2 = 0 := by
      have e : (x * r * y) ^ 2 = x * r * (y * x) * (r * y) := by
        simp only [pow_two, mul_assoc]
      rw [e, hyx]
      simp only [mul_zero, zero_mul]
    exact eq_zero_of_pow_eq_zero h h1
  have hmem : ∀ r : S, x * r * y ∈ (⊥ : TwoSidedIdeal S) := by
    intro r
    rw [hall r]
    exact zero_mem _
  obtain hL | hR := hprime.mem_or_mem hmem
  · exact Or.inl ((TwoSidedIdeal.mem_bot _).mp hL)
  · exact Or.inr ((TwoSidedIdeal.mem_bot _).mp hR)

/-- In a periodic domain, every nonzero element is a unit: `e = a ^ (n-1)`
is a nonzero idempotent, hence the two-sided identity. -/
private lemma isUnit_of_ne_zero_of_periodic {S : Type*} [Ring S]
    [NoZeroDivisors S]
    (h : ∀ x : S, ∃ n : ℕ, 1 < n ∧ x ^ n = x)
    {a : S} (ha : a ≠ 0) : IsUnit a := by
  obtain ⟨n, hn, hnx⟩ := h a
  set e : S := a ^ (n - 1) with he
  have hne : n - 1 + 1 = n := by omega
  have han : a ^ n = a * e := by
    have h2 := pow_succ' a (n - 1)
    rw [hne, ← he] at h2
    exact h2
  have he0 : e ≠ 0 := by
    intro hcon
    apply ha
    have hae : a = a * e := hnx.symm.trans han
    rw [hcon, mul_zero] at hae
    exact hae
  have hsq : e ^ 2 = e := by
    have hexp : (n - 1) * 2 = n + (n - 2) := by omega
    have hexp2 : n - 2 + 1 = n - 1 := by omega
    rw [he, ← pow_mul, hexp, pow_add, hnx, ← pow_succ', hexp2, ← he]
  have hel : ∀ x : S, e * x = x := by
    intro x
    have e2 : e * e = e := by rw [← pow_two, hsq]
    have h0 : e * (e * x - x) = 0 := by
      calc e * (e * x - x) = e * (e * x) - e * x := by rw [mul_sub]
        _ = e * x - e * x := by rw [← mul_assoc, e2]
        _ = 0 := sub_self _
    have hsub : e * x - x = 0 := (mul_eq_zero_iff_left he0).mp h0
    exact sub_eq_zero.mp hsub
  have her : ∀ x : S, x * e = x := by
    intro x
    have e2 : e * e = e := by rw [← pow_two, hsq]
    have h0 : (x * e - x) * e = 0 := by
      calc (x * e - x) * e = (x * e) * e - x * e := by rw [sub_mul]
        _ = x * e - x * e := by rw [mul_assoc, e2]
        _ = 0 := sub_self _
    have h0' : e * (x * e - x) = 0 := mul_eq_zero_comm.mp h0
    have hsub : x * e - x = 0 := (mul_eq_zero_iff_left he0).mp h0'
    exact sub_eq_zero.mp hsub
  have he1 : e = 1 := by
    have h1 := hel 1
    rwa [mul_one] at h1
  by_cases hn2 : n = 2
  · subst hn2
    have hae' : a = e := by
      rw [he, show (2 : ℕ) - 1 = 1 from rfl]
      exact (pow_one a).symm
    rw [hae', he1]
    exact isUnit_one
  · have hn3 : 3 ≤ n := by omega
    refine ⟨⟨a, a ^ (n - 2), ?_, ?_⟩, rfl⟩
    · have hexp : n - 2 + 1 = n - 1 := by omega
      rw [← pow_succ', hexp, ← he, he1]
    · have hexp : n - 2 + 1 = n - 1 := by omega
      rw [← pow_succ, hexp, ← he, he1]

/-- An ideal containing `1` is everything. -/
private lemma eq_top_of_one_mem {P : TwoSidedIdeal R} (h : (1 : R) ∈ P) :
    P = ⊤ := by
  apply top_unique
  intro x _
  have hx : x * 1 ∈ P := TwoSidedIdeal.mul_mem_left _ _ _ h
  rwa [mul_one] at hx

/-- The quotient by a prime ideal is a prime ring. -/
private lemma prime_bot_quotient {P : TwoSidedIdeal R}
    (hP : IsPrimeIdeal P) :
    IsPrimeIdeal (⊥ : TwoSidedIdeal P.ringCon.Quotient) := by
  refine ⟨?_, fun a b hab => ?_⟩
  · intro hcon
    have h10 : (1 : P.ringCon.Quotient) = 0 := by
      have hmem : (1 : P.ringCon.Quotient) ∈ (⊥ : TwoSidedIdeal _) := by
        rw [hcon]
        exact TwoSidedIdeal.mem_top _
      exact (TwoSidedIdeal.mem_bot _).mp hmem
    have hker : (1 : R) ∈ TwoSidedIdeal.ker P.ringCon.mk' := by
      rw [TwoSidedIdeal.mem_ker, map_one]
      exact h10
    rw [TwoSidedIdeal.ker_ringCon_mk'] at hker
    exact hP.ne_top (eq_top_of_one_mem hker)
  · obtain ⟨a', rfl⟩ := P.ringCon.mk'_surjective a
    obtain ⟨b', rfl⟩ := P.ringCon.mk'_surjective b
    have hab0 : ∀ r : P.ringCon.Quotient,
        P.ringCon.mk' a' * r * P.ringCon.mk' b' = 0 := by
      intro r
      exact (TwoSidedIdeal.mem_bot _).mp (hab r)
    have hPmem : ∀ rt : R, a' * rt * b' ∈ P := by
      intro rt
      have h0 : P.ringCon.mk' (a' * rt * b') = 0 := by
        have h1 := hab0 (P.ringCon.mk' rt)
        rw [map_mul, map_mul]
        exact h1
      have hker : a' * rt * b' ∈ TwoSidedIdeal.ker P.ringCon.mk' := by
        rw [TwoSidedIdeal.mem_ker]
        exact h0
      rwa [TwoSidedIdeal.ker_ringCon_mk'] at hker
    obtain hL | hR := hP.mem_or_mem hPmem
    · left
      have hker : a' ∈ TwoSidedIdeal.ker P.ringCon.mk' := by
        rwa [← TwoSidedIdeal.ker_ringCon_mk' P] at hL
      have h0 : P.ringCon.mk' a' = 0 := (TwoSidedIdeal.mem_ker _).mp hker
      exact (TwoSidedIdeal.mem_bot _).mpr h0
    · right
      have hker : b' ∈ TwoSidedIdeal.ker P.ringCon.mk' := by
        rwa [← TwoSidedIdeal.ker_ringCon_mk' P] at hR
      have h0 : P.ringCon.mk' b' = 0 := (TwoSidedIdeal.mem_ker _).mp hker
      exact (TwoSidedIdeal.mem_bot _).mpr h0

/-- Periodicity descends to quotients. -/
private lemma periodic_quotient {P : TwoSidedIdeal R}
    (h : ∀ x : R, ∃ n : ℕ, 1 < n ∧ x ^ n = x) :
    ∀ x : P.ringCon.Quotient, ∃ n : ℕ, 1 < n ∧ x ^ n = x := by
  intro x
  obtain ⟨a, rfl⟩ := P.ringCon.mk'_surjective x
  obtain ⟨n, hn, hnx⟩ := h a
  refine ⟨n, hn, ?_⟩
  rw [← map_pow, hnx]

/-- The quotient by a proper ideal is nontrivial. -/
private lemma nontrivial_quotient {P : TwoSidedIdeal R} (hP : P ≠ ⊤) :
    Nontrivial P.ringCon.Quotient := by
  refine ⟨1, 0, ?_⟩
  intro hcon
  have hker : (1 : R) ∈ TwoSidedIdeal.ker P.ringCon.mk' := by
    rw [TwoSidedIdeal.mem_ker, map_one]
    exact hcon
  rw [TwoSidedIdeal.ker_ringCon_mk'] at hker
  exact hP (eq_top_of_one_mem hker)

/-- Characteristic zero is impossible under torsion: `(2 : D) ^ k = 1`
would force `2 ^ k = 1` in `ℕ`. -/
private lemma char0_torsion_false {D : Type*} [DivisionRing D] [CharP D 0]
    (htors : ∀ x : D, x ≠ 0 → ∃ k : ℕ, 1 ≤ k ∧ x ^ k = 1) : False := by
  have h2 : ((2 : ℕ) : D) ≠ 0 := by
    intro hcon
    rw [CharP.cast_eq_zero_iff D 0 2] at hcon
    exact absurd hcon (by decide)
  obtain ⟨k, hk, hkk⟩ := htors ((2 : ℕ) : D) h2
  have hcast : ((2 ^ k : ℕ) : D) = ((1 : ℕ) : D) := by
    rw [Nat.cast_pow, Nat.cast_one]
    exact hkk
  have hsub : (((2 ^ k - 1 : ℕ)) : D) = 0 := by
    have h1 : (1 : ℕ) ≤ 2 ^ k := Nat.pow_pos (by norm_num)
    rw [Nat.cast_sub h1, hcast, sub_self]
  rw [CharP.cast_eq_zero_iff D 0 (2 ^ k - 1), zero_dvd_iff] at hsub
  have h2k : 2 ^ k = 1 := by
    have hpos : 0 < 2 ^ k := Nat.pow_pos (by norm_num)
    omega
  have hk0 : k = 0 := by
    by_contra hc
    have hge : 1 ≤ k := Nat.pos_of_ne_zero hc
    have hle : 2 ^ 1 ≤ 2 ^ k :=
      Nat.pow_le_pow_right (show (2 : ℕ) > 0 by norm_num) hge
    omega
  omega

/-- A torsion division ring has prime characteristic. -/
private lemma exists_charP_prime {D : Type*} [DivisionRing D]
    (htors : ∀ x : D, x ≠ 0 → ∃ k : ℕ, 1 ≤ k ∧ x ^ k = 1) :
    ∃ p : ℕ, Fact p.Prime ∧ CharP D p := by
  have hchar0 : ¬ CharP D 0 :=
    fun h0 => @char0_torsion_false D _ h0 htors
  obtain ⟨p, hpchar⟩ := CharP.exists D
  have hp0 : p ≠ 0 := fun hcon => hchar0 (hcon ▸ hpchar)
  have hp1 : p ≠ 1 := @CharP.char_ne_one D _ _ p hpchar
  have hp2 : 2 ≤ p := by omega
  have hprime : p.Prime := @CharP.char_is_prime_of_two_le D _ _ p hpchar hp2
  exact ⟨p, ⟨hprime⟩, hpchar⟩

/-- A subalgebra of a division ring has no zero divisors. -/
private lemma noZeroDivisors_of_subalgebra {D : Type*} [DivisionRing D]
    {F : Type*} [CommRing F] [Algebra F D] (S : Subalgebra F D) :
    NoZeroDivisors S := by
  refine ⟨?_⟩
  intro x y h
  have hval : x.val * y.val = 0 := by
    have hcon := congrArg Subtype.val h
    simpa using hcon
  have hD := eq_zero_or_eq_zero_of_mul_eq_zero hval
  cases hD with
  | inl hx => exact Or.inl (Subtype.ext hx)
  | inr hy => exact Or.inr (Subtype.ext hy)

/-- The subalgebra generated by a nonzero torsion element over `ZMod p` is a
finite division ring containing it. Powers reduce mod the torsion order, so
`{1, a, ..., a ^ (m-1)}` spans. Stated for the concrete adjoin so later
lemmas can use `adjoin_induction`. -/
private lemma exists_finite_subfield {D : Type*} [DivisionRing D]
    (htors : ∀ x : D, x ≠ 0 → ∃ k : ℕ, 1 ≤ k ∧ x ^ k = 1)
    {p : ℕ} [Fact p.Prime] [CharP D p] [Algebra (ZMod p) D]
    {a : D} (ha : a ≠ 0) :
    ∃ (_ : DivisionRing (Algebra.adjoin (ZMod p) {a}))
      (_ : Finite (Algebra.adjoin (ZMod p) {a})),
      a ∈ Algebra.adjoin (ZMod p) {a} := by
  have : NeZero p := ⟨(Fact.out : p.Prime).pos.ne'⟩
  obtain ⟨m, hm, ham⟩ := htors a ha
  have hmpos : 0 < m := by omega
  have hred : ∀ k : ℕ, a ^ k = a ^ (k % m) := by
    intro k
    conv_lhs => rw [← Nat.div_add_mod k m]
    rw [pow_add, pow_mul, ham, one_pow, one_mul]
  set K : Subalgebra (ZMod p) D := Algebra.adjoin (ZMod p) {a} with hK
  have haK : a ∈ K := Algebra.self_mem_adjoin_singleton (ZMod p) a
  have hpowK : ∀ i : ℕ, a ^ i ∈ K := fun i => pow_mem haK i
  set s : Set K := (fun i : Fin m => (⟨a ^ (i.val), hpowK _⟩ : K)) '' Set.univ with hs
  have hsfin : s.Finite := by
    rw [hs]
    exact Set.Finite.image _ Set.finite_univ
  have hmem : ∀ i : ℕ, ∀ hi : i < m, (⟨a ^ i, hpowK i⟩ : K) ∈ s := by
    intro i hi
    rw [hs]
    exact ⟨⟨i, hi⟩, Set.mem_univ _, rfl⟩
  have hsub : ∀ y : K, y ∈ s → y ∈ Submodule.span (ZMod p) s :=
    fun y hy => SetLike.mem_coe.mp (Submodule.subset_span hy)
  have span_mul : ∀ u v : K, u ∈ Submodule.span (ZMod p) s →
      v ∈ Submodule.span (ZMod p) s → u * v ∈ Submodule.span (ZMod p) s := by
    intro u v hu hv
    induction hu using Submodule.span_induction with
    | mem g hg =>
      induction hv using Submodule.span_induction with
      | mem h hh =>
        rw [hs] at hh hg
        obtain ⟨⟨i, _⟩, _, rfl⟩ := hg
        obtain ⟨⟨j, _⟩, _, rfl⟩ := hh
        change ((⟨a ^ i, hpowK i⟩ : K) * ⟨a ^ j, hpowK j⟩ ∈
          Submodule.span (ZMod p) s)
        have heq : (⟨a ^ i, hpowK i⟩ : K) * ⟨a ^ j, hpowK j⟩ =
            ⟨a ^ ((i + j) % m), hpowK _⟩ := by
          apply Subtype.ext
          change a ^ i * a ^ j = a ^ ((i + j) % m)
          rw [← pow_add]
          exact hred (i + j)
        rw [heq]
        exact hsub _ (hmem _ (Nat.mod_lt _ hmpos))
      | zero =>
        rw [mul_zero]
        exact zero_mem _
      | add x y _ _ ihx ihy =>
        rw [mul_add]
        exact add_mem ihx ihy
      | smul c x _ ihx =>
        rw [mul_smul_comm]
        exact Submodule.smul_mem _ _ ihx
    | zero =>
      rw [zero_mul]
      exact zero_mem _
    | add x y _ _ ihx ihy =>
      rw [add_mul]
      exact add_mem ihx ihy
    | smul c x _ ihx =>
      rw [smul_mul_assoc]
      exact Submodule.smul_mem _ _ ihx
  have ha_red : a = a ^ (1 % m) := by
    by_cases hm1 : m = 1
    · subst hm1
      rw [Nat.mod_self, pow_zero]
      exact (pow_one a).symm.trans ham
    · have h1m : 1 < m := lt_of_le_of_ne hm (Ne.symm hm1)
      rw [Nat.mod_eq_of_lt h1m, pow_one]
  have h1K : ∀ t : (1 : D) ∈ K, (⟨1, t⟩ : K) ∈ Submodule.span (ZMod p) s := by
    intro t
    have heq : (⟨1, t⟩ : K) = ⟨a ^ 0, hpowK 0⟩ := Subtype.ext (pow_zero a).symm
    rw [heq]
    exact hsub _ (hmem 0 hmpos)
  have halgK : ∀ (r : ZMod p) (t : algebraMap (ZMod p) D r ∈ K),
      (⟨algebraMap (ZMod p) D r, t⟩ : K) ∈ Submodule.span (ZMod p) s := by
    intro r t
    have heq : (⟨algebraMap (ZMod p) D r, t⟩ : K) =
        r • (⟨1, by rw [← pow_zero a]; exact hpowK 0⟩ : K) := by
      apply Subtype.ext
      change algebraMap (ZMod p) D r = r • (1 : D)
      rw [Algebra.smul_def, mul_one]
    rw [heq]
    exact Submodule.smul_mem _ _ (h1K _)
  have haddK : ∀ (x y : D) (hx : x ∈ K) (hy : y ∈ K),
      (⟨x, hx⟩ : K) ∈ Submodule.span (ZMod p) s →
      (⟨y, hy⟩ : K) ∈ Submodule.span (ZMod p) s →
      ∀ t : x + y ∈ K, (⟨x + y, t⟩ : K) ∈ Submodule.span (ZMod p) s := by
    intro x y hx hy ihx ihy t
    have heq : (⟨x + y, t⟩ : K) = ⟨x, hx⟩ + ⟨y, hy⟩ := rfl
    rw [heq]
    exact add_mem ihx ihy
  have hmulK : ∀ (x y : D) (hx : x ∈ K) (hy : y ∈ K),
      (⟨x, hx⟩ : K) ∈ Submodule.span (ZMod p) s →
      (⟨y, hy⟩ : K) ∈ Submodule.span (ZMod p) s →
      ∀ t : x * y ∈ K, (⟨x * y, t⟩ : K) ∈ Submodule.span (ZMod p) s := by
    intro x y hx hy ihx ihy t
    have heq : (⟨x * y, t⟩ : K) = ⟨x, hx⟩ * ⟨y, hy⟩ := rfl
    rw [heq]
    exact span_mul _ _ ihx ihy
  have htop : Submodule.span (ZMod p) s = ⊤ := by
    apply top_unique
    intro x _
    have hxK : x.val ∈ Algebra.adjoin (ZMod p) {a} := by
      rw [← hK]
      exact x.property
    refine Algebra.adjoin_induction
      (p := fun y _ => ∀ t : y ∈ K, (⟨y, t⟩ : K) ∈ Submodule.span (ZMod p) s)
      (mem := ?_) (algebraMap := ?_) (add := ?_) (mul := ?_) hxK x.property
    · intro y hy t
      rw [Set.mem_singleton_iff] at hy
      subst y
      have heq : (⟨a, t⟩ : K) = ⟨a ^ (1 % m), hpowK _⟩ := Subtype.ext ha_red
      rw [heq]
      exact hsub _ (hmem _ (Nat.mod_lt _ hmpos))
    · intro r t
      exact halgK r t
    · intro x y hx hy ihx ihy t
      exact haddK x y hx hy (ihx hx) (ihy hy) t
    · intro x y hx hy ihx ihy t
      exact hmulK x y hx hy (ihx hx) (ihy hy) t
  have hspan : Module.Finite (ZMod p) ↥(Submodule.span (ZMod p) s) :=
    Module.Finite.span_of_finite _ hsfin
  have : Finite ↥(Submodule.span (ZMod p) s) :=
    Module.finite_of_finite (R := ZMod p) (M := ↥(Submodule.span (ZMod p) s))
  have hKfin : Finite K :=
    Finite.of_surjective
      (fun y : ↥(Submodule.span (ZMod p) s) => (y.val : K))
      (fun x => ⟨⟨x, by simp [htop]⟩, rfl⟩)
  have : NoZeroDivisors K := noZeroDivisors_of_subalgebra K
  have : Nontrivial K := ⟨1, 0, by
    intro h
    have h2 := congrArg Subtype.val h
    simp at h2⟩
  have : IsDomain K := IsDomain.mk
  have : Fintype K := Fintype.ofFinite K
  have : DecidableEq K := Classical.decEq K
  have : DivisionRing K := Fintype.divisionRingOfIsDomain K
  exact ⟨‹DivisionRing K›, hKfin, haK⟩

/-- Torsion elements have positive multiplicative order. -/
private lemma orderOf_pos_of_torsion {D : Type*} [DivisionRing D]
    (htors : ∀ x : D, x ≠ 0 → ∃ k : ℕ, 1 ≤ k ∧ x ^ k = 1)
    {a : D} (ha : a ≠ 0) : 0 < orderOf a := by
  rw [orderOf_pos_iff, isOfFinOrder_iff_pow_eq_one]
  obtain ⟨k, hk, hkk⟩ := htors a ha
  exact ⟨k, by omega, hkk⟩

/-- A period strictly below the order is impossible. -/
private lemma pow_period_contra {D : Type*} [DivisionRing D]
    {a : D} (ha : a ≠ 0) {n' : ℕ} (hn' : orderOf a = n') (_hpos : 0 < n')
    {i d : ℕ} (hbd : i + d < n') (hd : 0 < d) (hij : a ^ i = a ^ (i + d)) :
    False := by
  have h1 : a ^ d = 1 := by
    have hne0 : a ^ i ≠ 0 := pow_ne_zero i ha
    have h2 : a ^ i * 1 = a ^ i * a ^ d := by rw [mul_one, ← pow_add]; exact hij
    have h3 := mul_left_cancel₀ hne0 h2
    exact h3.symm
  have hdvd : orderOf a ∣ d := orderOf_dvd_of_pow_eq_one h1
  rw [hn'] at hdvd
  have hle : n' ≤ d := Nat.le_of_dvd hd hdvd
  omega

/-- Powers below the order are distinct. -/
private lemma pow_distinct_of_orderOf {D : Type*} [DivisionRing D]
    {a : D} (ha : a ≠ 0) {n' : ℕ} (hn' : orderOf a = n') (hpos : 0 < n')
    {i j : ℕ} (hi : i < n') (hj : j < n') (hij : a ^ i = a ^ j) : i = j := by
  rcases lt_trichotomy i j with hlt | rfl | hgt
  · obtain ⟨d, rfl⟩ := Nat.exists_eq_add_of_le (le_of_lt hlt)
    exfalso
    exact pow_period_contra ha hn' hpos hj (by omega) hij
  · rfl
  · obtain ⟨d, rfl⟩ := Nat.exists_eq_add_of_le (le_of_lt hgt)
    exfalso
    exact pow_period_contra ha hn' hpos hi (by omega) hij.symm

/-- Periodicity implies torsion in a division ring. -/
private lemma torsion_of_periodic_div {D : Type*} [DivisionRing D]
    (h : ∀ x : D, ∃ n : ℕ, 1 < n ∧ x ^ n = x) :
    ∀ x : D, x ≠ 0 → ∃ k : ℕ, 1 ≤ k ∧ x ^ k = 1 := by
  intro x hx
  obtain ⟨n, hn, hnx⟩ := h x
  refine ⟨n - 1, by omega, ?_⟩
  have h2 := pow_succ' x (n - 1)
  rw [show n - 1 + 1 = n by omega, hnx] at h2
  have h3 : x * 1 = x * x ^ (n - 1) := by rw [mul_one]; exact h2
  have h4 := mul_left_cancel₀ hx h3
  exact h4.symm

/-- Jacobson assembly, conditional on Herstein's torsion theorem: a
commutator `xy - yx ≠ 0` would survive in some prime quotient, which is a
periodic division ring, hence commutative. -/
private lemma jacobson_of_herstein.{u} {R : Type u} [Ring R]
    (h : ∀ x : R, ∃ n : ℕ, 1 < n ∧ x ^ n = x)
    (herstein : ∀ {D : Type u} [DivisionRing D],
      (∀ x : D, ∃ n : ℕ, 1 < n ∧ x ^ n = x) → ∀ x y : D, x * y = y * x) :
    ∀ x y : R, x * y = y * x := by
  intro x y
  by_contra hne
  have ha : x * y - y * x ≠ 0 := sub_ne_zero.mpr hne
  obtain ⟨P, hPprime, hPmem⟩ := exists_primeIdeal_not_mem h ha
  have hPne : P ≠ ⊤ := hPprime.ne_top
  have := nontrivial_quotient hPne
  have hperQ := periodic_quotient h (P := P)
  have : NoZeroDivisors P.ringCon.Quotient :=
    noZeroDivisors_of_prime_of_periodic (prime_bot_quotient hPprime) hperQ
  let divInst : DivisionRing P.ringCon.Quotient :=
    DivisionRing.ofIsUnitOrEqZero (fun a => by
      by_cases haz : a = 0
      · exact Or.inr haz
      · exact Or.inl (isUnit_of_ne_zero_of_periodic hperQ haz))
  -- Bridge: quotient `^` is the `DivisionRing` power, proved by induction
  -- on representatives (the two `Pow` instances differ definitionally).
  have hbridge : ∀ (z : P.ringCon.Quotient) (n : ℕ),
      z ^ n = @NPow.npow _ (@Monoid.toNPow _
        (@Semiring.toMonoid _ (@DivisionSemiring.toSemiring _
          (@DivisionRing.toDivisionSemiring _ divInst)))) n z := by
    intro z n
    obtain ⟨a, rfl⟩ := P.ringCon.mk'_surjective z
    induction n with
    | zero => rfl
    | succ n ih =>
      have e1 : (P.ringCon.mk' a) ^ (n + 1) = P.ringCon.mk' (a ^ (n + 1)) := rfl
      have e2 : a ^ (n + 1) = a ^ n * a := pow_succ a n
      have e3 : @NPow.npow _ (@Monoid.toNPow _
              (@Semiring.toMonoid _ (@DivisionSemiring.toSemiring _
                (@DivisionRing.toDivisionSemiring _ divInst)))) (n + 1)
              (P.ringCon.mk' a)
          = @NPow.npow _ (@Monoid.toNPow _
              (@Semiring.toMonoid _ (@DivisionSemiring.toSemiring _
                (@DivisionRing.toDivisionSemiring _ divInst)))) n
              (P.ringCon.mk' a) * (P.ringCon.mk' a) := pow_succ _ _
      have e1' : P.ringCon.mk' (a ^ n) = (P.ringCon.mk' a) ^ n := rfl
      rw [e1, e2, map_mul, e1', ih, e3]
  have hperD : ∀ x : P.ringCon.Quotient, ∃ n : ℕ, 1 < n ∧
      @NPow.npow _ (@Monoid.toNPow _
        (@Semiring.toMonoid _ (@DivisionSemiring.toSemiring _
          (@DivisionRing.toDivisionSemiring _ divInst)))) n x = x := by
    intro z
    obtain ⟨n, hn, hnz⟩ := hperQ z
    refine ⟨n, hn, ?_⟩
    rw [← hbridge z n]
    exact hnz
  have hcomm := herstein (D := P.ringCon.Quotient) hperD
    (P.ringCon.mk' x) (P.ringCon.mk' y)
  have hcomm' : P.ringCon.mk' x * P.ringCon.mk' y =
      P.ringCon.mk' y * P.ringCon.mk' x := hcomm
  have h0 : P.ringCon.mk' (x * y - y * x) = 0 := by
    rw [map_sub, map_mul, map_mul, hcomm', sub_self]
  have hmem : x * y - y * x ∈ P := by
    have hker : x * y - y * x ∈ TwoSidedIdeal.ker P.ringCon.mk' := by
      rw [TwoSidedIdeal.mem_ker]
      exact h0
    rwa [TwoSidedIdeal.ker_ringCon_mk'] at hker
  exact hPmem hmem

/-- The endomorphism ring of `D` as a `ZMod p`-module has characteristic `p`. -/
private lemma charP_moduleEnd {D : Type*} [DivisionRing D] {p : ℕ} [CharP D p]
    [Algebra (ZMod p) D] : CharP (Module.End (ZMod p) D) p where
  cast_eq_zero_iff n := by
    constructor
    · intro h
      have h1 := congrArg (fun f : Module.End (ZMod p) D => f (1 : D)) h
      simp only [LinearMap.zero_apply] at h1
      have h2 : ((n : ℕ) : Module.End (ZMod p) D) (1 : D) = (n : D) := by
        rw [Module.End.natCast_apply, nsmul_eq_mul, mul_one]
      rw [h2] at h1
      exact (CharP.cast_eq_zero_iff D p n).mp h1
    · intro h
      obtain ⟨k, rfl⟩ := h
      apply LinearMap.ext
      intro x
      change ((p * k : ℕ) : Module.End (ZMod p) D) x = _
      rw [Nat.cast_mul, Module.End.mul_apply]
      have hp0 : ((p : ℕ) : Module.End (ZMod p) D) = 0 := by
        apply LinearMap.ext
        intro y
        change ((p : ℕ) : Module.End (ZMod p) D) y = _
        rw [Module.End.natCast_apply, LinearMap.zero_apply, nsmul_eq_mul,
          CharP.cast_eq_zero D p, zero_mul]
      rw [hp0]
      simp only [LinearMap.zero_apply]

/-- Left multiplication as a `ZMod p`-linear endomorphism. -/
private def lmulEnd {D : Type*} [DivisionRing D] {p : ℕ} [Algebra (ZMod p) D]
    (a : D) : Module.End (ZMod p) D where
  toFun x := a * x
  map_add' x y := mul_add a x y
  map_smul' c x := by
    change a * (c • x) = c • (a * x)
    rw [Algebra.smul_def, Algebra.smul_def, ← mul_assoc,
      ← (Algebra.commute_algebraMap_left c a).eq, mul_assoc]

/-- Right multiplication as a `ZMod p`-linear endomorphism. -/
private def rmulEnd {D : Type*} [DivisionRing D] {p : ℕ} [Algebra (ZMod p) D]
    (a : D) : Module.End (ZMod p) D where
  toFun x := x * a
  map_add' x y := add_mul x y a
  map_smul' c x := by
    change (c • x) * a = c • (x * a)
    rw [Algebra.smul_def, Algebra.smul_def, mul_assoc]

/-- The commutator operator `x ↦ a * x - x * a`. -/
private def commEnd {D : Type*} [DivisionRing D] {p : ℕ} [Algebra (ZMod p) D]
    (a : D) : Module.End (ZMod p) D :=
  lmulEnd a - rmulEnd a

private lemma lmulEnd_apply {D : Type*} [DivisionRing D] {p : ℕ}
    [Algebra (ZMod p) D] (a x : D) : lmulEnd (p := p) a x = a * x :=
  rfl

private lemma rmulEnd_apply {D : Type*} [DivisionRing D] {p : ℕ}
    [Algebra (ZMod p) D] (a x : D) : rmulEnd (p := p) a x = x * a :=
  rfl

private lemma commEnd_apply {D : Type*} [DivisionRing D] {p : ℕ}
    [Algebra (ZMod p) D] (a x : D) : commEnd (p := p) a x = a * x - x * a := by
  change (lmulEnd (p := p) a - rmulEnd (p := p) a) x = _
  rw [LinearMap.sub_apply]
  rfl

private lemma commute_lmul_rmul {D : Type*} [DivisionRing D] {p : ℕ}
    [Algebra (ZMod p) D] (a : D) :
    Commute (lmulEnd (p := p) a) (rmulEnd (p := p) a) := by
  change lmulEnd (p := p) a * rmulEnd (p := p) a = rmulEnd a * lmulEnd a
  ext x
  rw [Module.End.mul_apply, Module.End.mul_apply]
  change a * (x * a) = a * x * a
  exact (mul_assoc a x a).symm

private lemma lmulEnd_pow_apply {D : Type*} [DivisionRing D] {p : ℕ}
    [Algebra (ZMod p) D] (a : D) (n : ℕ) (x : D) :
    ((lmulEnd (p := p) a) ^ n) x = a ^ n * x := by
  induction n generalizing x with
  | zero => rw [pow_zero, Module.End.one_apply, pow_zero, one_mul]
  | succ n ih =>
    rw [pow_succ, Module.End.mul_apply, ih, lmulEnd_apply, ← mul_assoc,
      ← pow_succ]

private lemma rmulEnd_pow_apply {D : Type*} [DivisionRing D] {p : ℕ}
    [Algebra (ZMod p) D] (a : D) (n : ℕ) (x : D) :
    ((rmulEnd (p := p) a) ^ n) x = x * a ^ n := by
  induction n generalizing x with
  | zero => rw [pow_zero, Module.End.one_apply, pow_zero, mul_one]
  | succ n ih =>
    rw [pow_succ, Module.End.mul_apply, ih, rmulEnd_apply, mul_assoc,
      ← pow_succ']

/-- The commutator operator is idempotent under `p ^ n`-powering when
`a ^ (p ^ n) = a`: Frobenius on commuting one-sided multiplications. -/
private lemma commEnd_pow_of_pow_eq {D : Type*} [DivisionRing D] {p : ℕ}
    [Fact p.Prime] [CharP D p] [Algebra (ZMod p) D] {a : D} {n q : ℕ}
    (hq : q = p ^ n) (haq : a ^ q = a) :
    (commEnd (p := p) a) ^ q = commEnd a := by
  have := charP_moduleEnd (D := D) (p := p)
  have hpow := sub_pow_char_pow_of_commute (R := Module.End (ZMod p) D) p n
    (commute_lmul_rmul (p := p) a)
  change (lmulEnd a - rmulEnd a) ^ q = lmulEnd a - rmulEnd a
  rw [hq, hpow]
  have hl : lmulEnd (p := p) a ^ (p ^ n) = lmulEnd a := by
    ext x
    rw [lmulEnd_pow_apply]
    change a ^ (p ^ n) * x = a * x
    rw [← hq, haq]
  have hr : rmulEnd (p := p) a ^ (p ^ n) = rmulEnd a := by
    ext x
    rw [rmulEnd_pow_apply]
    change x * a ^ (p ^ n) = x * a
    rw [← hq, haq]
  rw [hl, hr]

/-- A subalgebra of a characteristic-`p` ring has characteristic `p`,
by injectivity of the inclusion. -/
private lemma charP_subalgebra {D : Type*} [DivisionRing D] {p : ℕ} [CharP D p]
    [Algebra (ZMod p) D] (K : Subalgebra (ZMod p) D) : CharP K p where
  cast_eq_zero_iff n := by
    have hinj : Function.Injective (K.val : K →+* D) := fun x y h => Subtype.ext h
    constructor
    · intro h
      have h2 := congrArg (⇑K.val) h
      rw [map_natCast, map_zero] at h2
      exact (CharP.cast_eq_zero_iff D p n).mp h2
    · intro h
      apply hinj
      rw [map_natCast, map_zero]
      exact (CharP.cast_eq_zero_iff D p n).mpr h

/-- Left multiplication by embedded field elements, as a ring hom into `End`.
Takes a plain field type plus embedding to avoid `Semiring` diamonds on
subalgebra coercions inside `Polynomial`. -/
private def lmulEndHom {D : Type*} [DivisionRing D] {p : ℕ}
    [Algebra (ZMod p) D] {K : Type*} [Semiring K] (val : K →+* D) :
    K →+* Module.End (ZMod p) D where
  toFun u := lmulEnd (val u)
  map_one' := by
    ext x
    rw [lmulEnd_apply, map_one, one_mul, Module.End.one_apply]
  map_mul' u v := by
    ext x
    rw [lmulEnd_apply, Module.End.mul_apply, lmulEnd_apply, lmulEnd_apply,
      map_mul, mul_assoc]
  map_zero' := by
    ext x
    rw [lmulEnd_apply, map_zero, zero_mul, LinearMap.zero_apply]
  map_add' u v := by
    ext x
    rw [lmulEnd_apply, LinearMap.add_apply, lmulEnd_apply, lmulEnd_apply,
      map_add, add_mul]

/-- Applying the bundled left-multiplication map is multiplication. -/
private lemma lmulEndHom_apply {D : Type*} [DivisionRing D] {p : ℕ}
    [Algebra (ZMod p) D] {K : Type*} [Semiring K] (val : K →+* D)
    (v : K) (x : D) : (lmulEndHom (p := p) val v) x = val v * x :=
  rfl

/-- Embedded-field left-multiplications commute with the commutator operator,
since embedded elements commute with `a`. -/
private lemma commute_lmulEndHom_commEnd {D : Type*} [DivisionRing D] {p : ℕ}
    [Algebra (ZMod p) D] {K : Type*} [Semiring K] (val : K →+* D) {a : D}
    (hcommKa : ∀ u : K, val u * a = a * val u) (u : K) :
    Commute (lmulEndHom (p := p) val u) (commEnd (p := p) a) := by
  change lmulEnd (val u) * (lmulEnd a - rmulEnd a)
    = (lmulEnd a - rmulEnd a) * lmulEnd (val u)
  ext x
  rw [Module.End.mul_apply, Module.End.mul_apply]
  change val u * ((commEnd (p := p) a) x)
    = (commEnd (p := p) a) (val u * x)
  rw [commEnd_apply, commEnd_apply, mul_sub]
  rw [show val u * (a * x) = a * (val u * x) from by
    rw [← mul_assoc, ← mul_assoc, hcommKa u]]
  rw [show val u * (x * a) = (val u * x) * a from (mul_assoc _ _ _).symm]

/-- `X ^ q - X` over a finite field is the product of `X - u`. -/
private lemma X_pow_card_sub_X_eq_prod {K : Type*} [Field K] [Fintype K] :
    Polynomial.X ^ Fintype.card K - Polynomial.X =
      ∏ u : K, (Polynomial.X - Polynomial.C u) := by
  classical
  have hq1 : 1 < Fintype.card K := Fintype.one_lt_card
  have hdeg : (Polynomial.X ^ Fintype.card K - Polynomial.X :
      Polynomial K).natDegree = Fintype.card K := by
    rw [Polynomial.natDegree_sub_eq_left_of_natDegree_lt]
    · exact Polynomial.natDegree_X_pow _
    · rw [Polynomial.natDegree_X_pow, Polynomial.natDegree_X]
      exact hq1
  have hsplit : (Polynomial.X ^ Fintype.card K - Polynomial.X :
      Polynomial K).Splits := by
    rw [Polynomial.splits_iff_card_roots,
      FiniteField.roots_X_pow_card_sub_X, Finset.card_val,
      Finset.card_univ, hdeg]
  have hmonic : (Polynomial.X ^ Fintype.card K - Polynomial.X :
      Polynomial K).Monic :=
    Polynomial.Monic.sub_of_left (Polynomial.monic_X_pow _)
      (by rw [Polynomial.degree_X, Polynomial.degree_X_pow]; exact Nat.cast_lt.mpr hq1)
  rw [hsplit.eq_prod_roots_of_monic hmonic,
    FiniteField.roots_X_pow_card_sub_X]
  rfl

/-- The factorization with `X` moved right, so evaluation puts `d` last. -/
private lemma X_pow_card_sub_X_eq_erase_mul {K : Type*} [Field K] [Fintype K]
    [DecidableEq K] :
    Polynomial.X ^ Fintype.card K - Polynomial.X =
      (∏ u ∈ Finset.univ.erase (0 : K),
        (Polynomial.X - Polynomial.C u)) * Polynomial.X := by
  classical
  rw [X_pow_card_sub_X_eq_prod,
    ← Finset.mul_prod_erase _ _ (Finset.mem_univ (0 : K)),
    map_zero, sub_zero, mul_comm]

/-- Evaluating the factorization at the commutator operator: `R * d = 0`,
with `R` as a list product since `End` is noncommutative. -/
private lemma prod_erase_mul_commEnd_eq_zero {D : Type*} [DivisionRing D]
    {p : ℕ} [Fact p.Prime] [CharP D p] [Algebra (ZMod p) D]
    {K : Type*} [Field K] [Fintype K] [DecidableEq K] (val : K →+* D)
    {a : D}
    (hcommKa : ∀ u : K, val u * a = a * val u)
    {n : ℕ} {q : ℕ} (hq : q = p ^ n) (hqq : Fintype.card K = q)
    (haq : a ^ q = a) :
    (((Finset.univ.erase (0 : K)).toList.map
      (fun u => commEnd (p := p) a - lmulEndHom (p := p) val u)).prod) *
      commEnd (p := p) a = 0 := by
  classical
  set α : Polynomial K →+* Module.End (ZMod p) D :=
    Polynomial.eval₂RingHom' (lmulEndHom (p := p) val) (commEnd (p := p) a)
      (fun u => commute_lmulEndHom_commEnd (p := p) val hcommKa u) with hα
  have hαX : α Polynomial.X = commEnd (p := p) a := by simp [hα]
  have hαC : ∀ u : K, α (Polynomial.C u) = lmulEndHom (p := p) val u := by
    intro u
    simp [hα]
  have hpoly := X_pow_card_sub_X_eq_erase_mul (K := K)
  rw [hqq] at hpoly
  have hα : α (Polynomial.X ^ q - Polynomial.X) =
      α ((∏ u ∈ Finset.univ.erase (0 : K),
        (Polynomial.X - Polynomial.C u)) * Polynomial.X) := by rw [hpoly]
  have hdq : (commEnd (p := p) a) ^ q = commEnd (p := p) a :=
    commEnd_pow_of_pow_eq hq haq
  rw [map_sub, map_pow, hαX, hdq, sub_self] at hα
  rw [map_mul, ← Finset.prod_map_toList, map_list_prod] at hα
  have hmap : ((Finset.univ.erase (0 : K)).toList.map
        (fun u => Polynomial.X - Polynomial.C u)).map α
      = (Finset.univ.erase (0 : K)).toList.map
        (fun u => commEnd (p := p) a - lmulEndHom (p := p) val u) := by
    rw [List.map_map]
    apply List.map_congr_left
    intro u _
    change α (Polynomial.X - Polynomial.C u) = _
    rw [map_sub, hαX, hαC u]
  rw [hmap, hαX] at hα
  exact hα.symm

/-- Power reduction from `a ^ q = a`: every power is a power below `q`. -/
private lemma pow_reduce_of_pow_eq {D : Type*} [DivisionRing D] {a : D} {q : ℕ}
    (ha : a ≠ 0) (hq2 : 2 ≤ q) (haq : a ^ q = a) (e : ℕ) :
    a ^ e = a ^ (if e = 0 then 0 else 1 + (e - 1) % (q - 1)) := by
  by_cases he : e = 0
  · rw [ite_eq_left he, he]
  · rw [ite_eq_right he]
    have he1 : 0 < e := Nat.pos_of_ne_zero he
    have hq1 : q - 1 + 1 = q := by omega
    have h1 : a ^ (q - 1) = 1 := by
      have h2 : a * a ^ (q - 1) = a * 1 := by
        rw [← pow_succ', hq1, haq, mul_one]
      exact mul_left_cancel₀ ha h2
    have hee : e = (e - 1) + 1 := (Nat.succ_pred_eq_of_pos he1).symm
    conv_lhs => rw [hee, ← Nat.div_add_mod (e - 1) (q - 1), pow_add, pow_add,
      pow_mul, h1, one_pow, one_mul, pow_one, ← pow_succ]
    rw [add_comm (1 : ℕ) _]

/-- Elements of `adjoin {a}` lie in the span of `{a ^ s : s < q}`. -/
private lemma mem_span_pow_of_mem_adjoin {D : Type*} [DivisionRing D] {p : ℕ}
    [Algebra (ZMod p) D] {a : D} {q : ℕ} (ha : a ≠ 0) (hq2 : 2 ≤ q)
    (haq : a ^ q = a) {H : D} (hH : H ∈ Algebra.adjoin (ZMod p) {a}) :
    H ∈ Submodule.span (ZMod p)
      ((fun i : Fin q => a ^ (i.val)) '' Set.univ) := by
  have h1q : 1 < q := by omega
  have h0q : 0 < q := by omega
  have memE : ∀ s : ℕ, s < q → a ^ s ∈
      (fun i : Fin q => a ^ (i.val)) '' Set.univ := by
    intro s hs
    exact ⟨⟨s, hs⟩, Set.mem_univ _, rfl⟩
  have spanE : ∀ s : ℕ, s < q → a ^ s ∈ Submodule.span (ZMod p)
      ((fun i : Fin q => a ^ (i.val)) '' Set.univ) := fun s hs =>
    Submodule.subset_span (memE s hs)
  have hred : ∀ e : ℕ, a ^ e ∈ Submodule.span (ZMod p)
      ((fun i : Fin q => a ^ (i.val)) '' Set.univ) := by
    intro e
    by_cases he : e = 0
    · rw [he]
      exact spanE 0 h0q
    · rw [pow_reduce_of_pow_eq ha hq2 haq e, ite_eq_right he]
      apply spanE
      have hmod : (e - 1) % (q - 1) < q - 1 := Nat.mod_lt _ (by omega)
      omega
  have span_mul : ∀ u v : D, u ∈ Submodule.span (ZMod p)
        ((fun i : Fin q => a ^ (i.val)) '' Set.univ) →
        v ∈ Submodule.span (ZMod p)
        ((fun i : Fin q => a ^ (i.val)) '' Set.univ) →
        u * v ∈ Submodule.span (ZMod p)
        ((fun i : Fin q => a ^ (i.val)) '' Set.univ) := by
    intro u v hu hv
    induction hu using Submodule.span_induction with
    | mem g hg =>
      induction hv using Submodule.span_induction with
      | mem h hh =>
        obtain ⟨⟨s, _⟩, _, rfl⟩ := hg
        obtain ⟨⟨t, _⟩, _, rfl⟩ := hh
        rw [← pow_add]
        exact hred _
      | zero =>
        rw [mul_zero]
        exact zero_mem _
      | add x y _ _ ihx ihy =>
        rw [mul_add]
        exact add_mem ihx ihy
      | smul c x _ ihx =>
        rw [mul_smul_comm]
        exact Submodule.smul_mem _ _ ihx
    | zero =>
      rw [zero_mul]
      exact zero_mem _
    | add x y _ _ ihx ihy =>
      rw [add_mul]
      exact add_mem ihx ihy
    | smul c x _ ihx =>
      rw [smul_mul_assoc]
      exact Submodule.smul_mem _ _ ihx
  refine Algebra.adjoin_induction
    (p := fun y _ => y ∈ Submodule.span (ZMod p)
      ((fun i : Fin q => a ^ (i.val)) '' Set.univ))
    (mem := ?_) (algebraMap := ?_) (add := ?_) (mul := ?_) hH
  · intro y hy
    rw [Set.mem_singleton_iff] at hy
    rw [hy]
    have h1mem := spanE 1 h1q
    rwa [pow_one] at h1mem
  · intro r
    have h1mem : (1 : D) ∈ Submodule.span (ZMod p)
        ((fun i : Fin q => a ^ (i.val)) '' Set.univ) := by
      have h10 : (1 : D) = a ^ 0 := (pow_zero a).symm
      rw [h10]
      exact spanE 0 h0q
    have hsm : algebraMap (ZMod p) D r = r • (1 : D) := by
      rw [Algebra.smul_def, mul_one]
    rw [hsm]
    exact Submodule.smul_mem _ _ h1mem
  · intro x y _ _ ihx ihy
    exact add_mem ihx ihy
  · intro x y _ _ ihx ihy
    exact span_mul x y ihx ihy

/-- If `b * a = c * b` with `c` in the finite subfield, then `a * b = b * a`:
the subalgebra generated by `a, b` is finite, hence a field by Wedderburn. -/
private lemma eq_of_almost_commute {D : Type*} [DivisionRing D] {p : ℕ}
    [Fact p.Prime] [CharP D p] [Algebra (ZMod p) D]
    (htors : ∀ x : D, x ≠ 0 → ∃ k : ℕ, 1 ≤ k ∧ x ^ k = 1)
    {a : D} (ha : a ≠ 0)
    {Ka : Subalgebra (ZMod p) D} [Field Ka] [Fintype Ka]
    (hKa : ∀ H : D, H ∈ Ka → H ∈ Algebra.adjoin (ZMod p) {a})
    {q : ℕ} (hq2 : 2 ≤ q) (hqq : Fintype.card Ka = q) (haq : a ^ q = a)
    {b : D} {c : Ka} (hba : b * a = (c : D) * b) :
    a * b = b * a := by
  classical
  by_cases hb : b = 0
  · rw [hb, mul_zero, zero_mul]
  · obtain ⟨t, ht1, hbt⟩ := htors b hb
    have ht0 : 0 < t := by omega
    have h1q : 1 < q := by omega
    have h0q : 0 < q := by omega
    have hredB : ∀ f : ℕ, b ^ f = b ^ (f % t) := by
      intro f
      conv_lhs => rw [← Nat.div_add_mod f t]
      rw [pow_add, pow_mul, hbt, one_pow, one_mul]
    have hmod : ∀ j : ℕ, j % t < t := fun j => Nat.mod_lt j ht0
    set E : Set D := (fun p : ℕ × ℕ => a ^ (p.1) * b ^ (p.2)) ''
      {p : ℕ × ℕ | p.1 < q ∧ p.2 < t} with hE
    have hEfin : E.Finite := by
      have hset : {p : ℕ × ℕ | p.1 < q ∧ p.2 < t}
          = ↑(Finset.range q ×ˢ Finset.range t) := by
        ext ⟨i, j⟩
        simp
      rw [hE, hset]
      exact Set.Finite.image _ (Finset.finite_toSet _)
    have memE : ∀ i j : ℕ, i < q → j < t → a ^ i * b ^ j ∈ E := by
      intro i j hi hj
      exact ⟨(i, j), ⟨hi, hj⟩, rfl⟩
    have spanE : ∀ i j : ℕ, i < q → j < t →
        a ^ i * b ^ j ∈ Submodule.span (ZMod p) E := fun i j hi hj =>
      Submodule.subset_span (memE i j hi hj)
    have hba_pow : ∀ r : ℕ, b * a ^ r = (c : D) ^ r * b := by
      intro r
      induction r with
      | zero => rw [pow_zero, pow_zero, one_mul, mul_one]
      | succ r ih =>
        rw [pow_succ, ← mul_assoc, ih, pow_succ, mul_assoc, hba, ← mul_assoc]
    have hmove : ∀ j s : ℕ, ∃ H : D, H ∈ Algebra.adjoin (ZMod p) {a} ∧
        b ^ j * a ^ s = H * b ^ j := by
      intro j
      induction j with
      | zero =>
        intro s
        exact ⟨a ^ s, pow_mem (Algebra.subset_adjoin (Set.mem_singleton a)) s,
          by rw [pow_zero, one_mul, mul_one]⟩
      | succ j ih =>
        intro s
        obtain ⟨Hj, hHjK, hHj⟩ := ih s
        have key : ∀ H : D, H ∈ Submodule.span (ZMod p)
              ((fun i : Fin q => a ^ (i.val)) '' Set.univ) →
              ∃ H2 : D, H2 ∈ Algebra.adjoin (ZMod p) {a} ∧ b * H = H2 * b := by
          intro H hH
          induction hH using Submodule.span_induction with
          | mem y hy =>
            obtain ⟨⟨r, _⟩, _, rfl⟩ := hy
            refine ⟨((c ^ r : Ka) : D), hKa _ (c ^ r).property, ?_⟩
            rw [Subalgebra.coe_pow]
            exact hba_pow r
          | zero =>
            exact ⟨0, zero_mem _, by rw [mul_zero, zero_mul]⟩
          | add x y _ _ ihx ihy =>
            obtain ⟨X, hXK, hX⟩ := ihx
            obtain ⟨Y, hYK, hY⟩ := ihy
            exact ⟨X + Y, add_mem hXK hYK, by rw [mul_add, hX, hY, ← add_mul]⟩
          | smul d x _ ihx =>
            obtain ⟨X, hXK, hX⟩ := ihx
            refine ⟨algebraMap (ZMod p) D d * X,
              mul_mem ((Algebra.adjoin (ZMod p) {a}).algebraMap_mem d)
                hXK, ?_⟩
            rw [Algebra.smul_def, ← mul_assoc,
              (Algebra.commute_algebraMap_left d b).symm.eq, mul_assoc, hX,
              ← mul_assoc]
        have hspan := mem_span_pow_of_mem_adjoin ha hq2 haq hHjK
        obtain ⟨Ht, hHtK, hHt⟩ := key Hj hspan
        refine ⟨Ht, hHtK, ?_⟩
        calc b ^ (j + 1) * a ^ s = b * (b ^ j * a ^ s) := by
              conv_lhs => rw [pow_succ']
              rw [mul_assoc]
          _ = b * (Hj * b ^ j) := by rw [hHj]
          _ = (b * Hj) * b ^ j := by rw [← mul_assoc]
          _ = (Ht * b) * b ^ j := by rw [hHt]
          _ = Ht * b ^ (j + 1) := by rw [mul_assoc, ← pow_succ']
    have key2 : ∀ H : D, H ∈ Submodule.span (ZMod p)
          ((fun i : Fin q => a ^ (i.val)) '' Set.univ) →
          ∀ i j : ℕ, a ^ i * H * b ^ j ∈ Submodule.span (ZMod p) E := by
      intro H hH
      induction hH using Submodule.span_induction with
      | mem y hy =>
        obtain ⟨w, _, rfl⟩ := hy
        intro i j
        rw [← pow_add]
        by_cases h0 : i + w.val = 0
        · rw [h0, pow_zero, one_mul, hredB]
          have h1 : b ^ (j % t) = a ^ 0 * b ^ (j % t) := by
            rw [pow_zero, one_mul]
          rw [h1]
          exact spanE 0 (j % t) h0q (hmod j)
        · rw [pow_reduce_of_pow_eq ha hq2 haq, ite_eq_right h0, hredB]
          apply spanE
          · have hmod' : (i + w.val - 1) % (q - 1) < q - 1 :=
              Nat.mod_lt _ (by omega)
            omega
          · exact hmod j
      | zero =>
        intro i j
        rw [mul_zero, zero_mul]
        exact zero_mem _
      | add x y _ _ ihx ihy =>
        intro i j
        rw [mul_add, add_mul]
        exact add_mem (ihx i j) (ihy i j)
      | smul d x _ ihx =>
        intro i j
        have heq : a ^ i * (d • x) * b ^ j = d • (a ^ i * x * b ^ j) := by
          rw [mul_smul_comm, smul_mul_assoc]
        rw [heq]
        exact Submodule.smul_mem _ _ (ihx i j)
    have span_mul : ∀ u v : D, u ∈ Submodule.span (ZMod p) E →
        v ∈ Submodule.span (ZMod p) E → u * v ∈ Submodule.span (ZMod p) E := by
      intro u v hu hv
      induction hu using Submodule.span_induction with
      | mem g hg =>
        induction hv using Submodule.span_induction with
        | mem h hh =>
          obtain ⟨⟨i, j⟩, ⟨hi, hj⟩, rfl⟩ := hg
          obtain ⟨⟨s, l⟩, ⟨hs, hl⟩, rfl⟩ := hh
          obtain ⟨H, hHK, hH⟩ := hmove j s
          have hspanH := mem_span_pow_of_mem_adjoin ha hq2 haq hHK
          have hmem := key2 H hspanH i (j + l)
          have hHeq : (a ^ i * b ^ j) * (a ^ s * b ^ l)
              = a ^ i * H * b ^ (j + l) := by
            calc (a ^ i * b ^ j) * (a ^ s * b ^ l)
                = a ^ i * ((b ^ j * a ^ s) * b ^ l) := by
                  rw [mul_assoc, ← mul_assoc (b ^ j) _ _]
              _ = a ^ i * ((H * b ^ j) * b ^ l) := by rw [hH]
              _ = a ^ i * H * b ^ (j + l) := by
                  rw [mul_assoc, mul_assoc, ← pow_add]
          change (a ^ i * b ^ j) * (a ^ s * b ^ l) ∈ _
          rw [hHeq]
          exact hmem
        | zero =>
          rw [mul_zero]
          exact zero_mem _
        | add x y _ _ ihx ihy =>
          rw [mul_add]
          exact add_mem ihx ihy
        | smul c x _ ihx =>
          rw [mul_smul_comm]
          exact Submodule.smul_mem _ _ ihx
      | zero =>
        rw [zero_mul]
        exact zero_mem _
      | add x y _ _ ihx ihy =>
        rw [add_mul]
        exact add_mem ihx ihy
      | smul c x _ ihx =>
        rw [smul_mul_assoc]
        exact Submodule.smul_mem _ _ ihx
    set S : Subalgebra (ZMod p) D := Algebra.adjoin (ZMod p) {a, b} with hS
    have haS : a ∈ S := Algebra.subset_adjoin (by simp)
    have hbS : b ∈ S := Algebra.subset_adjoin (by simp)
    have hSM : ∀ x : D, x ∈ S → x ∈ Submodule.span (ZMod p) E := by
      intro x hx
      refine Algebra.adjoin_induction
        (p := fun y _ => y ∈ Submodule.span (ZMod p) E)
        (mem := ?_) (algebraMap := ?_) (add := ?_) (mul := ?_) hx
      · intro y hy
        rw [Set.mem_insert_iff, Set.mem_singleton_iff] at hy
        rcases hy with hy | hy
        · rw [hy]
          have hmem := spanE 1 0 h1q ht0
          rwa [pow_one, pow_zero, mul_one] at hmem
        · rw [hy]
          by_cases ht1' : 1 < t
          · have hmem := spanE 0 1 h0q ht1'
            rwa [pow_zero, pow_one, one_mul] at hmem
          · have ht1eq : t = 1 := by omega
            have hb1 : b = 1 := by
              have h := hbt
              rwa [ht1eq, pow_one] at h
            subst hb1
            have hmem := spanE 0 0 h0q (by omega)
            rwa [pow_zero, pow_zero, mul_one] at hmem
      · intro r
        have h1mem : (1 : D) ∈ Submodule.span (ZMod p) E := by
          have hmem := spanE 0 0 h0q (by omega)
          rwa [pow_zero, pow_zero, mul_one] at hmem
        have hsm : algebraMap (ZMod p) D r = r • (1 : D) := by
          rw [Algebra.smul_def, mul_one]
        rw [hsm]
        exact Submodule.smul_mem _ _ h1mem
      · intro x y _ _ ihx ihy
        exact add_mem ihx ihy
      · intro x y _ _ ihx ihy
        exact span_mul x y ihx ihy
    have hMS : Submodule.span (ZMod p) E ≤ S.toSubmodule := by
      rw [Submodule.span_le]
      intro y hy
      obtain ⟨⟨i, j⟩, ⟨hi, hj⟩, rfl⟩ := hy
      change a ^ i * b ^ j ∈ S
      exact mul_mem (pow_mem haS i) (pow_mem hbS j)
    have hMfin : Module.Finite (ZMod p) ↥(Submodule.span (ZMod p) E) :=
      Module.Finite.span_of_finite _ hEfin
    have hSfin : Finite S := by
      have hfinM : Finite ↥(Submodule.span (ZMod p) E) :=
        Module.finite_of_finite (R := ZMod p) (M := ↥(Submodule.span (ZMod p) E))
      exact Finite.of_injective
        (fun x : S => (⟨(x : D), hSM _ x.property⟩ :
          ↥(Submodule.span (ZMod p) E)))
        (fun x y h => by simpa using h)
    have : NoZeroDivisors S := noZeroDivisors_of_subalgebra S
    have : Nontrivial S := ⟨1, 0, by
      intro h
      have h2 := congrArg Subtype.val h
      simp at h2⟩
    have : IsDomain S := IsDomain.mk
    have : Fintype S := Fintype.ofFinite S
    have : DecidableEq S := Classical.decEq S
    -- Wedderburn commutativity via explicit terms (NOT instances: the
    -- derived `Field S` would diamond against the subalgebra `Mul`).
    -- The constructions reuse the ambient `Mul`, so this is defeq.
    have hcomm : ∀ x y : S, x * y = y * x :=
      (@littleWedderburn S (Fintype.divisionRingOfIsDomain S)
        hSfin).toCommRing.toCommMonoid.toCommSemigroup.toCommMagma.mul_comm
    have h1 := hcomm (⟨a, haS⟩ : S) (⟨b, hbS⟩ : S)
    have e1 : Subtype.val ((⟨a, haS⟩ : S) * (⟨b, hbS⟩ : S)) = a * b :=
      Subalgebra.coe_mul _ _ _
    have e2 : Subtype.val ((⟨b, hbS⟩ : S) * (⟨a, haS⟩ : S)) = b * a :=
      Subalgebra.coe_mul _ _ _
    have h2 := congrArg Subtype.val h1
    rw [e1, e2] at h2
    exact h2

/-- A list product of injective endomorphisms is injective. -/
private lemma list_prod_injective {D : Type*} [DivisionRing D] {p : ℕ}
    [Algebra (ZMod p) D] {l : List (Module.End (ZMod p) D)}
    (h : ∀ f ∈ l, Function.Injective ⇑f) :
    Function.Injective ⇑l.prod := by
  induction l with
  | nil =>
    rw [List.prod_nil]
    exact Function.injective_id
  | cons f l ih =>
    rw [List.prod_cons]
    have h1 := h f List.mem_cons_self
    have h2 := ih (fun g hg => h g (List.mem_cons_of_mem f hg))
    rw [Module.End.coe_mul]
    exact h1.comp h2

/-- Each factor `d - λ_u` (for `u ≠ 0`) is injective: from
`(d - λ_u) b = 0` we get `b * a = (a - u) * b`, hence `a * b = b * a`,
hence `u * b = 0`, hence `b = 0`. -/
private lemma inj_factor {D : Type*} [DivisionRing D] {p : ℕ}
    [Fact p.Prime] [CharP D p] [Algebra (ZMod p) D]
    (htors : ∀ x : D, x ≠ 0 → ∃ k : ℕ, 1 ≤ k ∧ x ^ k = 1)
    {a : D} (ha : a ≠ 0)
    {Ka : Subalgebra (ZMod p) D} [Field Ka] [Fintype Ka]
    (haKa : a ∈ Ka)
    (hKa : ∀ H : D, H ∈ Ka → H ∈ Algebra.adjoin (ZMod p) {a})
    {q : ℕ} (hq2 : 2 ≤ q) (hqq : Fintype.card Ka = q) (haq : a ^ q = a)
    {u : Ka} (hu : u ≠ 0) :
    Function.Injective
      ⇑(commEnd (p := p) a - lmulEndHom (p := p) Ka.val.toRingHom u) := by
  suffices hker : ∀ b : D,
      (commEnd (p := p) a - lmulEndHom (p := p) Ka.val.toRingHom u) b
        = 0 → b = 0 by
    intro b1 b2 h
    have h0 : (commEnd (p := p) a - lmulEndHom (p := p) Ka.val.toRingHom u)
        (b1 - b2) = 0 := by
      rw [map_sub, h, sub_self]
    have := hker _ h0
    exact sub_eq_zero.mp this
  intro b hb0
  rw [LinearMap.sub_apply, commEnd_apply, lmulEndHom_apply] at hb0
  have h1 : a * b - b * a = (Ka.val.toRingHom u : D) * b :=
    sub_eq_zero.mp hb0
  have h3 : a * b = (Ka.val.toRingHom u : D) * b + b * a :=
    sub_eq_iff_eq_add.mp h1
  have h2 : b * a = a * b - (Ka.val.toRingHom u : D) * b := by
    rw [h3, add_sub_cancel_left]
  have hbau : b * a = (a - (Ka.val.toRingHom u : D)) * b := by
    rw [h2, ← sub_mul]
  set c' : Ka := (⟨a, haKa⟩ : Ka) - u with hc'
  have hc'val : ((c' : Ka) : D) = a - (Ka.val.toRingHom u : D) := by
    rw [hc', Subalgebra.coe_sub]
    simp
  have hba' : b * a = ((c' : Ka) : D) * b := by
    rw [hc'val]
    exact hbau
  have hab := eq_of_almost_commute htors ha hKa hq2 hqq haq hba'
  rw [hab, sub_self] at h1
  have hu0 : (Ka.val.toRingHom u : D) ≠ 0 := by
    intro hcon
    apply hu
    apply Subtype.ext
    change Ka.val.toRingHom u = Ka.val.toRingHom 0
    rw [hcon, map_zero]
  have h0 : (Ka.val.toRingHom u : D) * b = 0 := h1.symm
  rcases mul_eq_zero.mp h0 with h | h
  · exact absurd h hu0
  · exact h

/-- Herstein's torsion theorem, via the Wamsley/Nagahara-Tominaga operator
argument: a periodic division ring is commutative. -/
private lemma herstein_of_torsion {D : Type*} [DivisionRing D] {p : ℕ}
    [Fact p.Prime] [CharP D p] [Algebra (ZMod p) D]
    (htors : ∀ x : D, x ≠ 0 → ∃ k : ℕ, 1 ≤ k ∧ x ^ k = 1) :
    ∀ a b : D, a * b = b * a := by
  classical
  intro a
  by_cases ha : a = 0
  · intro b
    rw [ha, zero_mul, mul_zero]
  · obtain ⟨_, hfinKa, haKa⟩ := exists_finite_subfield htors ha
    -- The `DivisionRing` from `exists_finite_subfield` is opaque, so rebuild
    -- it transparently; keep `Field`/`DivisionRing` OUT of TC to avoid
    -- diamonds against the subalgebra ring (cf. chunk 4d).
    have hfinKaI : Finite (Algebra.adjoin (ZMod p) {a}) := hfinKa
    have : NoZeroDivisors (Algebra.adjoin (ZMod p) {a}) :=
      noZeroDivisors_of_subalgebra (Algebra.adjoin (ZMod p) {a})
    have : Nontrivial (Algebra.adjoin (ZMod p) {a}) := ⟨1, 0, by
      intro h
      have h2 := congrArg Subtype.val h
      simp at h2⟩
    have : IsDomain (Algebra.adjoin (ZMod p) {a}) := IsDomain.mk
    have hfinTI : Fintype (Algebra.adjoin (ZMod p) {a}) := Fintype.ofFinite _
    have hdeTI : DecidableEq (Algebra.adjoin (ZMod p) {a}) := Classical.decEq _
    have hcharT : CharP (Algebra.adjoin (ZMod p) {a}) p :=
      charP_subalgebra (Algebra.adjoin (ZMod p) {a})
    obtain ⟨n, -, hqn⟩ := @FiniteField.card (Algebra.adjoin (ZMod p) {a})
      (@littleWedderburn (Algebra.adjoin (ZMod p) {a})
        (Fintype.divisionRingOfIsDomain (Algebra.adjoin (ZMod p) {a})) hfinKa)
      hfinTI p hcharT
    have hq2 : 2 ≤ Fintype.card (Algebra.adjoin (ZMod p) {a}) :=
      Fintype.one_lt_card
    have haq : a ^ Fintype.card (Algebra.adjoin (ZMod p) {a}) = a := by
      have hK := @FiniteField.pow_card (Algebra.adjoin (ZMod p) {a})
        ((@DivisionRing.toDivisionSemiring (Algebra.adjoin (ZMod p) {a})
          (Fintype.divisionRingOfIsDomain
            (Algebra.adjoin (ZMod p) {a}))).toGroupWithZero) hfinTI
        (⟨a, haKa⟩ : Algebra.adjoin (ZMod p) {a})
      have h2 := congrArg Subtype.val hK
      rw [Subalgebra.coe_pow] at h2
      exact h2
    have hcommKa : ∀ u : Algebra.adjoin (ZMod p) {a},
        (((u : D)) * a = a * ((u : D))) := by
      intro u
      have hmul_comm : ∀ x y : Algebra.adjoin (ZMod p) {a}, x * y = y * x :=
        ((@littleWedderburn (Algebra.adjoin (ZMod p) {a})
          (Fintype.divisionRingOfIsDomain (Algebra.adjoin (ZMod p) {a}))
          hfinKa)).toCommRing.toCommMonoid.toCommSemigroup.toCommMagma.mul_comm
      have h := hmul_comm u (⟨a, haKa⟩ : Algebra.adjoin (ZMod p) {a})
      have h2 := congrArg Subtype.val h
      rw [Subalgebra.coe_mul, Subalgebra.coe_mul] at h2
      exact h2
    have hKa : ∀ H : D, H ∈ Algebra.adjoin (ZMod p) {a} →
        H ∈ Algebra.adjoin (ZMod p) {a} := fun H hH => hH
    set R' : Module.End (ZMod p) D :=
      (((Finset.univ.erase (0 : Algebra.adjoin (ZMod p) {a})).toList.map
        (fun u => commEnd (p := p) a -
          lmulEndHom (p := p)
            (Algebra.adjoin (ZMod p) {a}).val.toRingHom u)).prod) with hR'Def
    have hRd : R' * commEnd (p := p) a = 0 :=
      @prod_erase_mul_commEnd_eq_zero D _ p _ _ _
        (Algebra.adjoin (ZMod p) {a})
        (@littleWedderburn (Algebra.adjoin (ZMod p) {a})
          (Fintype.divisionRingOfIsDomain (Algebra.adjoin (ZMod p) {a})) hfinKa)
        hfinTI hdeTI
        (Algebra.adjoin (ZMod p) {a}).val.toRingHom a
        hcommKa (n : ℕ) (Fintype.card (Algebra.adjoin (ZMod p) {a}))
        hqn rfl haq
    have hRinj : Function.Injective ⇑R' := by
      apply list_prod_injective
      intro f hf
      simp only [List.mem_map] at hf
      obtain ⟨u, hu, rfl⟩ := hf
      rw [Finset.mem_toList] at hu
      have hu0 : u ≠ 0 := by
        intro hcon
        rw [hcon] at hu
        simp at hu
      exact @inj_factor D _ p _ _ _ htors a ha
        (Algebra.adjoin (ZMod p) {a})
        (@littleWedderburn (Algebra.adjoin (ZMod p) {a})
          (Fintype.divisionRingOfIsDomain (Algebra.adjoin (ZMod p) {a})) hfinKa)
        hfinTI haKa hKa
        (Fintype.card (Algebra.adjoin (ZMod p) {a})) hq2 rfl haq u hu0
    have hd0 : commEnd (p := p) a = 0 := by
      apply LinearMap.ext
      intro x
      have hRx : R' ((commEnd (p := p) a) x) = 0 := by
        have hRx0 : (R' * commEnd (p := p) a) x = 0 := by
          rw [hRd, LinearMap.zero_apply]
        rw [Module.End.mul_apply] at hRx0
        exact hRx0
      exact hRinj (by rw [hRx, LinearMap.zero_apply, map_zero])
    intro b
    have hdb : (commEnd (p := p) a) b = 0 := by
      rw [hd0, LinearMap.zero_apply]
    rw [commEnd_apply] at hdb
    exact sub_eq_zero.mp hdb

/-- Jacobson's commutativity theorem: a ring in which every element
satisfies `x ^ n = x` for some `n > 1` is commutative. -/
theorem jacobson_commutativity {R : Type*} [Ring R]
    (h : ∀ x : R, ∃ n : ℕ, 1 < n ∧ x ^ n = x) :
    ∀ x y : R, x * y = y * x := by
  apply jacobson_of_herstein h
  intro D _ hper
  have htors : ∀ x : D, x ≠ 0 → ∃ k : ℕ, 1 ≤ k ∧ x ^ k = 1 :=
    torsion_of_periodic_div hper
  obtain ⟨p, hp, hchar⟩ := exists_charP_prime htors
  have := hp
  have := hchar
  let : Algebra (ZMod p) D := ZMod.algebra D p
  exact herstein_of_torsion htors

end Int.Ring.JacobsonCommutativity
