
import Mathlib.Algebra.Lie.Free


namespace MetaMathlibExt

variable (K : Type) [Field K] {r : ℕ}

/-- A homogeneous Lie monomial in the canonical generators of
`FreeLieAlgebra K (Fin r)`, indexed by its multidegree.

A canonical generator `i` is a monomial whose multidegree is `1` at `i` and
`0` elsewhere; the Lie bracket of monomials of multidegrees `a` and `b` is a
monomial of pointwise multidegree `fun i => a i + b i`. -/
inductive IsFreeLieMonomial : (Fin r → ℕ) → FreeLieAlgebra K (Fin r) → Prop where
  | gen (i : Fin r) :
      IsFreeLieMonomial (Function.update (fun _ => 0) i 1) (FreeLieAlgebra.of K i)
  | bracket {a b : Fin r → ℕ} {x y : FreeLieAlgebra K (Fin r)} :
      IsFreeLieMonomial a x → IsFreeLieMonomial b y →
        IsFreeLieMonomial (fun i => a i + b i) (Bracket.bracket x y)

/-- Multihomogeneous component of a finitely generated free Lie algebra: the
`K`-submodule of `FreeLieAlgebra K (Fin r)` generated by homogeneous Lie
monomials in the `r` canonical generators where generator `i` occurs exactly
`degree i` times. It uses the actual `FreeLieAlgebra K (Fin r)` and
distinguishes multidegrees, not only total bracket length.

Source: Pieter Moree, *Convoluted Convolved Fibonacci Numbers*, Journal of
Integer Sequences 7 (2004), Article 04.2.2, Witt's formula paragraph (the
subspace `H` generated by homogeneous elements of multidegree
`(n₁, …, nᵣ)`), lines 621–628,
<https://cs.uwaterloo.ca/journals/JIS/VOL7/Moree/moree12.tex>. -/
noncomputable def freeLieMultihomogeneousComponent (degree : Fin r → ℕ) :
    Submodule K (FreeLieAlgebra K (Fin r)) :=
  Submodule.span K { x | IsFreeLieMonomial K degree x }

end MetaMathlibExt
